name: Atualizar EPG a cada 10 minutos

on:
  schedule:
    - cron: '*/10 * * * *'  # A cada 10 minutos
  workflow_dispatch:        # Permite execução manual

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Instalar dependências
        run: sudo apt update && sudo apt install -y wget gzip

      - name: Baixar e descompactar o EPG
        run: |
          wget -O epg.xml.gz "https://epgshare01.online/epgshare01/epg_ripper_BR1.xml.gz"
          gunzip -f epg.xml.gz

      - name: Criar timestamp para forçar commit
        run: date -u +"%Y-%m-%dT%H:%M:%SZ" > .timestamp.txt

      - name: Commit e push (forçado)
        run: |
          git config --global user.email "github-actions@users.noreply.github.com"
          git config --global user.name "github-actions"
          git add epg.xml .timestamp.txt
          git commit -m "EPG atualizado: $(cat .timestamp.txt)"
          git remote remove origin
          git remote add origin https://${{ secrets.GH_PAT }}@github.com/silverfb13/epg-auto.git
          git push origin HEAD:main
